<?php

namespace App\Tests\Service;

use App\Entity\Cursus;
use App\Entity\Lesson;
use App\Entity\User;
use App\Repository\CursusValidationRepository;
use App\Repository\LessonValidationRepository;
use App\Service\CertificationService;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\TestCase;

class CertificationServiceTest extends TestCase
{
    private function createCursusWithTwoLessons(): array
    {
        $cursus = new Cursus();
        $cursus->setName('Test cursus');
        $cursus->setPrice(40);

        // The id is normally generated by the database; we set it here
        // so the mocked repository methods (which expect an int) can be called.
        $reflection = new \ReflectionProperty(Cursus::class, 'id');
        $reflection->setValue($cursus, 1);

        $lesson1 = new Lesson();
        $lesson1->setTitle('Lesson 1');
        $lesson1->setPrice(20);
        $lesson1->setCursus($cursus);
        $cursus->addLesson($lesson1);

        $lesson2 = new Lesson();
        $lesson2->setTitle('Lesson 2');
        $lesson2->setPrice(20);
        $lesson2->setCursus($cursus);
        $cursus->addLesson($lesson2);

        return [$cursus, $lesson1, $lesson2];
    }

    // Validating the only remaining lesson of a cursus must trigger the
    // automatic certification (CursusValidation)
    public function testValidatingTheLastLessonCertifiesTheCursus(): void
    {
        [$cursus, $lesson1, $lesson2] = $this->createCursusWithTwoLessons();
        $user = new User();

        $lessonValidationRepository = $this->createMock(LessonValidationRepository::class);
        $lessonValidationRepository->method('isLessonValidatedByUser')->willReturn(false);
        // Both lessons are now validated
        $lessonValidationRepository->method('countValidatedLessonsForCursus')->willReturn(2);

        $cursusValidationRepository = $this->createMock(CursusValidationRepository::class);
        $cursusValidationRepository->method('isCursusValidatedByUser')->willReturn(false);

        $entityManager = $this->createMock(EntityManagerInterface::class);
        // persist/flush is called once for the LessonValidation, once for the CursusValidation
        $entityManager->expects($this->exactly(2))->method('persist');
        $entityManager->expects($this->exactly(2))->method('flush');

        $service = new CertificationService($entityManager, $lessonValidationRepository, $cursusValidationRepository);
        $service->validateLesson($user, $lesson2);
    }

    // Validating a lesson while some others are still missing must NOT
    // certify the cursus yet
    public function testValidatingOneLessonDoesNotCertifyIfOthersAreMissing(): void
    {
        [$cursus, $lesson1, $lesson2] = $this->createCursusWithTwoLessons();
        $user = new User();

        $lessonValidationRepository = $this->createMock(LessonValidationRepository::class);
        $lessonValidationRepository->method('isLessonValidatedByUser')->willReturn(false);
        // Only 1 of the 2 lessons is validated
        $lessonValidationRepository->method('countValidatedLessonsForCursus')->willReturn(1);

        $cursusValidationRepository = $this->createMock(CursusValidationRepository::class);
        $cursusValidationRepository->expects($this->never())->method('isCursusValidatedByUser');

        $entityManager = $this->createMock(EntityManagerInterface::class);
        // Only the LessonValidation is persisted, no CursusValidation
        $entityManager->expects($this->once())->method('persist');
        $entityManager->expects($this->once())->method('flush');

        $service = new CertificationService($entityManager, $lessonValidationRepository, $cursusValidationRepository);
        $service->validateLesson($user, $lesson1);
    }

    // Validating an already-validated lesson must do nothing (idempotent)
    public function testValidatingAnAlreadyValidatedLessonDoesNothing(): void
    {
        [$cursus, $lesson1] = $this->createCursusWithTwoLessons();
        $user = new User();

        $lessonValidationRepository = $this->createMock(LessonValidationRepository::class);
        $lessonValidationRepository->method('isLessonValidatedByUser')->willReturn(true);

        $cursusValidationRepository = $this->createMock(CursusValidationRepository::class);

        $entityManager = $this->createMock(EntityManagerInterface::class);
        $entityManager->expects($this->never())->method('persist');
        $entityManager->expects($this->never())->method('flush');

        $service = new CertificationService($entityManager, $lessonValidationRepository, $cursusValidationRepository);
        $service->validateLesson($user, $lesson1);
    }
}
